### ISSUE TITLE
[Feature] Timeline

### ISSUE THREAD

**Issue by rhnmht30** [dsckiet/website#34]
# Overview
 
 A separate timeline page containing cards showing all past journeys and achievements.

# Description

 DSC KIET website is an official website made with HTML, CSS, and JAVASCRIPT. This website describes the organization's workflow, events, and members.

# Expected Outcomes

A timeline to show our journey in DSC.

Includes: 
 - life events (parties, trips, etc)
 - milestones
 - achievements
 - talks/sessions (w/ photos)
 - Twitter/instagram post

# Skills

 HTML, CSS, JAVASCRIPT.

# Possible Mentors

 [Avaneesh Singh](https://github.com/avi-11)

# Expected Time

 8 days

# Difficulty

 Hard

**Comment by hamidKMB** [comment]
hey there can i work on this feature ?
need some information to start work on it

**Comment by avi-11** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by avi-11** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

### Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll Create regular Blog posts on the progress of the project
● I’ll try my best to complete the project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.
<hr>

---

**Comment by devanshu0605** [comment]
Will be making a Events page and current/recent event

About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 8 Months . I
have experience in HTML , CSS , JavaScript, and UNITY 3D and I am currently learning Dart .

Issue - [Feature] Events page and current/recent event

Proposed Solution….
● Will form a Event page .
● Will make a Recent and past events page
● Will Implement Animations in these pages through javascript .

TimeLine
Sept 11- Sept 12
Event Page formation work with animations

Sept 12- Sept 13
Will submit the project
Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll add animations in this project for its attractiveness
● I’ll complete this project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.

**Comment by devanshu0605** [comment]
A separate timeline page containing cards showing all past journeys and achievements.

About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 8 Months . I
have experience in HTML , CSS , JavaScript, and UNITY 3D and I am currently learning Dart .

Issue - [Feature] Timeline

Proposed Solution….
● Will form a Event page .
● Will make a Recent and past events page
● Will Implement Animations in these pages through javascript .

TimeLine
Sept 11- Sept 12
Event Page formation work with animations

Sept 12- Sept 13
Will submit the project
Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll add animations in this project for its attractiveness
● I’ll complete this project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.

**Comment by avi-11** [comment]
ok @devanshu0605  you can proceed on to build the functionality.

just read the readme.md and contributing.md to get more knowledge.

I'll assign you the task and you can ask any doubts regarding anything here.

**Comment by devanshu0605** [comment]
A separate timeline page containing cards showing all past journeys and achievements.

About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 8 Months . I
have experience in HTML , CSS , JavaScript, and UNITY 3D and I am currently learning Dart .

Issue - [Feature] Timeline

Proposed Solution….
● Will form a Event page .
● Will make a Recent and past events page
● Will Implement Animations in these pages through javascript .

TimeLine
Sept 11- Sept 12
Event Page formation work with animations

Sept 12- Sept 13
Will submit the project
Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll add animations in this project for its attractiveness
● I’ll complete this project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance
