### ISSUE TITLE
Footer Update

### ISSUE THREAD

**Issue by avi-11** [dsckiet/website#49]
# Overview
 
 Re-construct the Footer, with proper links and colors along with hover options on nav links.

# Description

 DSC KIET website is an official website made with HTML, CSS, and JAVASCRIPT. This website describes the organization's workflow, events, and members.

# Expected Outcomes

 A smooth and proper footer along with proper UI.

# Skills

 HTML, CSS, JAVASCRIPT.

# Possible Mentors

 [Avaneesh Singh](https://github.com/avi-11)

# Expected Time

 2 days

# Difficulty

 Easy

**Comment by avi-11** [comment]
# Use This Proposal Template as a Reference to write your own proposal for Msoc

# Your Issue Name

### Your Background and Technical Skills.
<hr>

### What problem are you trying to solve and Your Approach?
<hr>

###  Your Timeline to solve the problem.
<hr>

### Your Commitments.
<hr>

---

**Comment by avi-11** [comment]
# Example of Proposal.


# Improve the generated PDF in the PDF/LaTeX backend

### About me
I have been programming since High School and I have been Advocating for Open-Source projects for the past 2 years. I
have experienced in Python , JavaScript, and Dart[Flutter] and I am currently learning Julia. I organized events on Open-Source in my College and I am the founding member of an Open-Source community [fossc](https://www.saynotocp.org/) where I mentor Students in their Open-Source Journey. For more information about me You can head over to my [website](https://kanishkpachauri.netlify.app/)
<hr>

### Issue - Intermittent CI failures with PDF builds 
Issue - The "PDF/LaTeX backend" stage often fails on CI, causing the docs not to deploy (since they only deploy if that stage passes) Restarting the build usually fixes it though.

## Proposed Solution….
● Fixing any bug on the CI end.
● Debug any issue in the test of the LaTeX backend
● Rewriting guided Tests for it so that it can be fixed throughout the process.
<hr>

###  TimeLine
## May 20 - June 12
Community bonding, understanding Documenter.jl Codebase, re-scoping project implementation/timeline with help from mentors.

## June 13 - June 23
Learning Julia Essentials and other essentials for integration and fixing of issue #1196 and #1467 and #1342 .

## June 24 - July 15
Adding the Proposed Solution for the issue #1196 and #1467

<hr>

### Commitments.
● I’ll try my best to learn everything which is essential for the
project.
● I’ll Create regular Blog posts on the progress of the project
● I’ll try my best to complete the project on time.
● In case of any change in the above timeline, I will inform
the mentors in advance.
<hr>

---

**Comment by ShreyashSriv** [comment]
### **FOOTER UPDATE**

### **Background and Technical Skills.**
I am Shreyash Srivastava I have around a year of experience in HTML CSS and JavaScript and I am a rookie in REACT JS.
I found about MSOC from my friends in DSC KIet and want to start my open source contributiions.

### What problem are you trying to solve and Your Approach?
I am approaching the redesign of the footer with minimalist look which provides info without being an eysore

 ### Your Timeline to solve the problem.
10th September - I have already forked the repository and started to look and the issue and it will take around 1 day to fix it.

 ### Your Commitments.
I am commited to give my all in order to solve this issue ASAP.

**Comment by Hackintosh-02** [comment]
> # Footer Redesign
> ### Your Background and Technical Skills.
I am Ashutosh Sharma I am relatively new to Web Designing with around 4 months of experience and I want to start my open source contributions, I have worked on designs on Figma and think I can resolve this issue.
> ### What problem are you trying to solve and Your Approach?
- I will differentiate diffferent segments and give them a better contrasting look.
> ### Your Timeline to solve the problem.
I am going to start on 11th September and the project will be finished around 13th September.
> ### Your Commitments.
I am committed to giving my all in order to solve this issue ASAP.

**Comment by avi-11** [comment]
ok @ShreyashSriv  you can proceed on to build the functionality.

just read the readme.md and contributing.md to get more knowledge.

I'll assign you the task and you can ask any doubts regarding anything here.

**Comment by ShreyashSriv** [comment]
@avi-11 sorry for the delays but due to technical problems in my laptop I need your help in the setup of the react app of dsc would you please help me set up my environment.

**Comment by avi-11** [comment]
yeah we can meet tomorrow,is that fine?

**Comment by ShreyashSriv** [comment]
@avi-11 yes
